### ISSUE TITLE
怎么删除已经部署到服务器的应用？

### ISSUE THREAD

**Issue by CodeLYQ** [romejiang/meteorup#11]

**Comment by romejiang** [comment]
如果是私有部署是使用pm2管理nodejs项目，所以可以这样查看和删除项目
```
pm2 ls
pm2 delete 0  // 或者
pm2 delete project_name

```

[具体pm2的使用方法看这里](http://pm2.keymetrics.io/docs/usage/quick-start/)

**Comment by CodeLYQ** [comment]
@romejiang  谢谢，已经成功删除项目。

**Comment by CodeLYQ** [comment]
@romejiang  还有个问题，我想清除项目的相关文件。是不是找到相应路径，手动删除就行？
ps:我的package.json 设置如下：
...
  "setup": {
    "mongo": false,
    "path": "/usr/local/meteorup"
  },
...

**Comment by romejiang** [comment]
是的

**Comment by CodeLYQ** [comment]
@romejiang  好的，明白了，谢谢。
