### ISSUE TITLE
YJENV 有哪些配置项？

### ISSUE THREAD

**Issue by yz89** [romejiang/meteorup#4]
`
"env": {
          "YJENV": "test",
          ...}
`

**Comment by romejiang** [comment]
YJENV只是一个例子，你可以在env中配置任意名称的环境变量。然后再程序中这样访问：process.env.YJENV，但这种访问仅限于 server 端代码，如果想在 server 端和 client 端同时访问环境变量，需要一个特殊的配置：METEOR_SETTINGS

``` js
"deploy": {
    "appName": "xxx",
    "env": {
      "METEOR_SETTINGS": "{\\\"public\\\" : {\\\"server\\\":\\\"true\\\"}}",
      "MONGO_URL": "mongodb://127.0.0.1:27017/hcw",
      "ROOT_URL": "http://www.xxx.com/",
      "CDN_URL": "http://xxxxxxx.bkt.clouddn.com",
      "PORT": 3000
    }
  }
```

上面的代码是一个真实的 package.json 文件的一部分，在server 端和 client 端可以通过 Meteor.settings.public.server 访问到 METEOR_SETTINGS 配置项里的内容。

具体细节看 Meteor 文档：
https://docs.meteor.com/api/core.html#Meteor-settings

**Comment by yz89** [comment]
好的  感谢
